### ISSUE TITLE
Log to sys.stdout only on request

### ISSUE THREAD

**Issue by hackerb9** [dbazile/gaudible#6]
First: Thank you for sharing gaudible with everyone and taking the time to tell people about it on Ask Ubuntu. It works great, and I'm glad to finally have a solution.

Currently, gaudible prints logs to stdout. However, running silently by default, unless requested via `--debug` or `--log-level=n`, would be better for people (like me) who only use your program and aren't modifying it. This could be done by raising the logging.basicConfig level to 'WARNING' instead of 'INFO'. (I'd suggest 'NOTICE', but it looks like older versions of the logging module didn't support that.)

Alternately, if it's not too hard in Python, gaudible could default to sending messages to syslog with facility set to “daemon”. 

Thanks!

**Comment by dbazile** [comment]
Bam (https://github.com/dbazile/gaudible/commit/3b6ba4882827e07305308a75f6d4f84d9b603848)
```diff
 def main():
     ap = argparse.ArgumentParser()
-    ap.add_argument('--debug', action='store_true')
+    ap.add_argument('-v', '--verbose', action='count', help='controls amount of log output (repeat for more verbosity)')
```

Give it a shot now. As for the other thing; I manually tapped into syslog once in my career and vowed never to do it willingly again, lol. :trollface:

**Comment by hackerb9** [comment]
Wow, that was fast! Works exactly as I hoped. Thanks!
