### ISSUE TITLE
librewolf

### ISSUE THREAD

**Issue by g1bber1sh** [dbazile/gaudible#7]
Hi!
I'm trying to get this to work with librewolf but it's not working. I've installed librewolf manually in /opt/librewolf, and created a symlink to the executable in  /usr/bin, but no sound :( 
It works with firefox though. Any suggestions?

This is on EndeavourOS (arch) gnome 43, Linux 6.0.10, everything up to date

Thanks

**Comment by dbazile** [comment]
Never heard of Librewolf before. Intriguing... :monocle_face: 

Anyway, if Librewolf is announcing notifications in the dbus queue, it should be observable. You'd just need to find the message properties to make a new filter.

First, run this in a terminal:
```
dbus-monitor 'type=method_call, interface=org.gtk.Notifications, member=AddNotification' \
             'type=method_call, interface=org.freedesktop.Notifications, member=Notify'
```

...then, in a Librewolf tab on a site you trust (or already have enabled notifications for), open the console and run this snippet:
```javascript
n = new Notification('wut')
```

dbus-monitor should dump something that looks like this:
```
method call time=1670095115.317904 sender=:1.105 -> destination=:1.49 serial=570 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Firefox"
   uint32 0
   string ""
   string "wut"
   string ""
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "sender-pid"
         variant             int64 4945
      )
   ]
   int32 -1
method call time=1670095115.319800 sender=:1.49 -> destination=:1.23 serial=698 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Firefox"
   uint32 0
   string ""
   string "wut"
   string ""
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "sender-pid"
         variant             uint32 4945
      )
   ]
   int32 -1
```

If you send me that blurb, I might be able to get you something that works.

**Comment by g1bber1sh** [comment]
Hi, thanks for reply. Librewolf is a firefox fork with all the telemetry removed. Anyway here is the output:

signal time=1670096994.480833 sender=org.freedesktop.DBus -> destination=:1.1368 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.1368"
signal time=1670096994.480846 sender=org.freedesktop.DBus -> destination=:1.1368 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.1368"
method call time=1670097001.586386 sender=:1.100 -> destination=:1.37 serial=35 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "LibreWolf"
   uint32 0
   string ""
   string "wut"
   string ""
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "sender-pid"
         variant             int64 38226
      )
   ]
   int32 -1
method call time=1670097001.587673 sender=:1.37 -> destination=:1.13 serial=40 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "LibreWolf"
   uint32 0
   string ""
   string "wut"
   string ""
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "sender-pid"
         variant             uint32 38226
      )
   ]
   int32 -1

**Comment by dbazile** [comment]
Just added as a filter in 0fdd1c1045b16feb1fd6d2de69d2715c1521d3bc. I don't have LibreWolf so can you give this branch a shot and let me know if it works?

https://github.com/dbazile/gaudible/tree/librewolf_support

**Comment by g1bber1sh** [comment]
Hey
That seems to work! I only did the console thing to test it out, no proper notifications arrived yet, but i guess if it works with the console command it means its working.
Thank you very much!

**Comment by dbazile** [comment]
NP!
